version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8083:8083"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
    ports:
      - "3003:3003"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
